models/About.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "about".
 *
 * @property int $id
 * @property string $title_ru
 * @property string $title_en
 * @property string $content_ru
 * @property string $content_en
 * @property string $param1_title_ru
 * @property string $param1_title_en
 * @property string $param1_content_ru
 * @property string $param1_content_uz
 * @property string $param2_title_ru
 * @property string $param2_title_en
 * @property string $param2_content_ru
 * @property string $param2_content_en
 * @property string $param3_title_ru
 * @property string $param3_title_en
 * @property string $param3_content_en
 * @property string $param3_content_ru
 */
class About extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'about';
    }

    public function behaviors()
    {
        return [
            [
                'class' => '\app\components\FileUploadBehaviour'
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['content_ru', 'content_en', 'param1_content_ru', 'param1_content_en', 'param2_content_ru', 'param2_content_en', 'param3_content_en', 'param3_content_ru'], 'string'],
            [['title_ru', 'title_en', 'param1_title_ru', 'param1_title_en', 'param2_title_ru', 'param2_title_en', 'param3_title_ru', 'param3_title_en'], 'string', 'max' => 255],
            [['path'],'file'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title_ru' => Yii::t('app', 'Title Ru'),
            'title_en' => Yii::t('app', 'Title En'),
            'content_ru' => Yii::t('app', 'Content Ru'),
            'content_en' => Yii::t('app', 'Content En'),
            'param1_title_ru' => Yii::t('app', 'Param1 Title Ru'),
            'param1_title_en' => Yii::t('app', 'Param1 Title En'),
            'param1_content_ru' => Yii::t('app', 'Param1 Content Ru'),
            'param1_content_en' => Yii::t('app', 'Param1 Content En'),
            'param2_title_ru' => Yii::t('app', 'Param2 Title Ru'),
            'param2_title_en' => Yii::t('app', 'Param2 Title En'),
            'param2_content_ru' => Yii::t('app', 'Param2 Content Ru'),
            'param2_content_en' => Yii::t('app', 'Param2 Content En'),
            'param3_title_ru' => Yii::t('app', 'Param3 Title Ru'),
            'param3_title_en' => Yii::t('app', 'Param3 Title En'),
            'param3_content_en' => Yii::t('app', 'Param3 Content En'),
            'param3_content_ru' => Yii::t('app', 'Param3 Content Ru'),
            'path' => Yii::t('app', 'Image'),
        ];
    }
    public function getParam1Title(){

        if (Yii::$app->language == 'ru'):  return $this->param1_title_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->param1_title_en;

        endif;
    }
    public function getParam1Content(){

        if (Yii::$app->language == 'ru'):  return $this->param1_content_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->param1_content_en;

        endif;
    }
    public function getParam2Title(){

        if (Yii::$app->language == 'ru'):  return $this->param2_title_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->param2_title_en;

        endif;
    }
    public function getParam2Content(){

        if (Yii::$app->language == 'ru'):  return $this->param2_content_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->param2_content_en;

        endif;
    }
    public function getParam3Title(){

        if (Yii::$app->language == 'ru'):  return $this->param3_title_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->param3_title_en;

        endif;
    }
    public function getParam3Content(){

        if (Yii::$app->language == 'ru'):  return $this->param3_content_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->param3_content_en;

        endif;
    }
    public function getTitle(){

        if (Yii::$app->language == 'ru'):  return $this->title_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->title_en;

        endif;
    }

    public function getContent(){

        if (Yii::$app->language == 'ru'):  return $this->content_ru;

        endif;
        if (Yii::$app->language == 'en'):  return $this->content_en;

        endif;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\About;
use app\models\Application;
use app\models\Carousel;
use app\models\Category;
use app\models\Contacts;
use app\models\forms\Login;
use app\models\Orders;
use app\models\OurService;
use app\models\OurServices;
use app\models\Phones;
use app\models\Rayon;
use app\models\Services;
use app\models\Sms;
use app\models\User;
use app\models\UserInfo;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\forms\ContactForm;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{

    public function init()
    {

        if (!empty(Yii::$app->request->cookies['language'])) {
            Yii::$app->language = Yii::$app->request->cookies['language'];
        } else {
            Yii::$app->language = 'ru';
        }
        parent::init();
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $carousel = Carousel::find()
            ->orderBy(['order' => SORT_ASC])
            ->all();
        $services = OurServices::find()
            ->where(['status' => 1])
            ->orderBy(['id' => SORT_DESC])
            ->limit(4)
            ->all();
        $categories = Category::find()
            ->limit(4)
            ->all();
        $advantages = Services::find()
            ->where(['status' => 1])
            ->all();


        return $this->render('index', compact([
            'carousel',
            'services',
            'categories',
            'advantages',
        ]));
    }

    /**
     * Login
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new Login();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            Yii::$app->session->setFlash('loginError');
//            return $this->refresh();
            return $this->goBack();

        }
    }


    /**
     * @return bool|string
     */
    public function actionSignUp()
    {
        //Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
        //$this->layout = false;
        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');

        $user = new User();
        $user->username = $username;
        $user->setPassword($password);
        $user->status = 0;
        if ($user->save()) {
            return $this->renderAjax('sign-up-ajax',['user' => $user]);
        }

        return false;

    }

    /**
     * @return bool|int|string
     */
    public function actionGetCode() {


        // render code for sms masssage
        $code = mt_rand(1000, 9999);

        $phone = Yii::$app->request->post('phone');
        $user_id = Yii::$app->request->post('id');
        $user = User::findOne($user_id);

        $user_info = new UserInfo();                // create User Info
        $user_info->user_id = $user_id;
        $user_info->phone = $phone;

        $sms = new Sms();                           // create SMS
        $sms->phone = $phone;
        $sms->sms = $code;                          // example sms = 1 || change
        $sms->send_at = time();
        $phone = substr($phone,1,12);    // format to 9989X XXX XXXX
        if ($user_info->save(false) && $sms->save(false) && Yii::$app->user->login($user)) {
            $sms->sendSMS($code,$phone);
            return $sms->id;
        }
    }

    /**
     * @return int
     */
    public function actionOrderGetCode() {

        // render code for sms masssage
        $code = mt_rand(1000, 9999);

        $phone = Yii::$app->request->get('phone');

        $sms = new Sms();                       // create SMS
        $sms->phone = $phone;
        $sms->sms = $code;                      // example sms = 1 || change
        $sms->send_at = time();
        $phone = substr($phone,1,12);    // format to 9989X XXX XXXX

        if ($sms->save(false)) {
            $sms->sendSMS($code,$phone);
            return $sms->id;
        }
    }


    /**
     * @return bool|int|Response
     */
    public function actionGetSms()
    {
        $sms = Yii::$app->request->get('sms');
        $sms = Sms::findOne($sms);
        $user_id = Yii::$app->request->get('id');
        $code = Yii::$app->request->get('code');
        $user = User::findOne($user_id);
        if(!empty($sms)){

            if($code == $sms->sms){

                $user = User::findOne($user_id);
                $user->status = 10;
                $user->save(false);
                Yii::$app->user->login($user);
                return $this->goHome();
            } else{
                return 2;
            }

        }
        return false;

    }

    /**
     * @return bool|int|Response
     */

    /**
     * Logout
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->getUser()->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContacts()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $about = About::find()->where(['id' => 1])->one();

        return $this->render('about', ['about' => $about]);
    }

    /**
     * @return string
     */
    public function actionDelivery()
    {
        $about = About::find()->where(['id' => 2])->one();

        return $this->render('delivery', ['about' => $about]);
    }

    /**
     * @return string
     */
    public function actionOurServices()
    {
        $our_service = OurService::find()->where(['id' => 1])->one();
        $our_services = OurServices::find()->where(['status' => 1])->all();
        return $this->render('our-services', compact([
            'our_service',
            'our_services',
        ]));
    }

    /**
     * @param $lang
     * @return Response
     */
    public function actionSetLanguage($lang)
    {
        $l = $lang;
        $langs = ['en', 'ru'];
        if (in_array($l, $langs)) {
            \Yii::$app->language = $l;
            Yii::$app->session->set('app_lang', $l);
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'language',
                'value' => $l,
            ]));
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @return string
     */
    public function actionContact()
    {
        $contact = Contacts::find()->where(['id' => 1])->one();
        $phones = Phones::find()->all();
        return $this->render('contacts', compact([
            'contact',
            'phones'
        ]));
    }

    /**
     * @return string
     */
    public function actionCabinet(){
        $user_id = Yii::$app->user->id;

        $orders = Orders::find()->where(['user_id' => $user_id])->all();
        $user = User::findOne($user_id);
        $user_info = UserInfo::find()->where(['user_id' => $user_id])->one();

        return $this->render('cabinet', compact([
            'user',
            'user_info',
            'orders',
        ]));

    }

    /**
     * @return Response
     */
    public function actionApplication(){
        $name = Yii::$app->request->post('name');
        $email = Yii::$app->request->post('email');
        $massege = Yii::$app->request->post('massege');

        $app = new Application();
        $app->name = $name;
        $app->email = $email;
        $app->massege = $massege;
        if($app->save()){
          Yii::$app->session->setFlash('app',true);
            return $this->redirect(Yii::$app->request->referrer);
        }

    }

    /**
     * @return string
     */
    public function actionChangeUser()
    {

        $id = Yii::$app->user->id;
        $user = User::findIdentity($id);
        $user_info = UserInfo::find()->where(['user_id' => $id])->one();

        $phone = Yii::$app->request->get('phone');
        $username = Yii::$app->request->get('username');
        $name = Yii::$app->request->get('name');
        $emial = Yii::$app->request->get('email');
        if (Yii::$app->request->get()) {
            $user->username = $username;
            $user->email = $emial;
            $user_info->name = $name;
            $user_info->phone = $phone;
            if ($user_info->save(false) && $user->save(false)) {

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
?>
<!-- |************************************************** Main **************************************************| -->
<main class="main">

    <!-- |=================================== Inner Banner ===================================| -->
    <section class="inner_bnr_sec">
        <div class="inner_bnr_bg bg-cover" style="background-image:url('/uploads/<?= $about->path ?>');     height: 400px;"></div>
        <!-- |========== Inner Banner ==========| -->
    </section>



    <!-- |=================================== About Us ===================================| -->
    <section class="abt_us_sec">
        <div class="product_bg bg-cover" style="background-image:url('/img/about_us/section_bg.png');"></div>

        <div class="container">
            <div class="abt_us">

                <div class="abt_us_desc">
                    <h3 class="inr_title abt_us_desc_ttl"><?= $about->title ?></h3>

                    <div class="abt_us_desc_cnt">
                        <?= $about->content ?>
                    </div>
                </div>


                <div class="abt_us_work">
                    <h2 class="base_title abt_us_work_ttl"><?= Yii::t('app','Для кого мы работаем?') ?></h2>

                    <div class="abt_us_work_cnt">
                        <div class="row">
                            <div class="col-4 abt_us_work_it">
                                <div class="abt_us_work_img fx-c">
                                    <img src="/img/about_us/about_us_1.png" alt="">
                                </div>

                                <div class="abt_us_work_name"><?= $about->param1Title ?></div>

                                <div class="abt_us_work_txt"><?= $about->param1Content ?>
                                </div>
                            </div>

                            <div class="col-4 abt_us_work_it">
                                <div class="abt_us_work_img fx-c">
                                    <img src="/img/about_us/about_us_2.png" alt="">
                                </div>

                                <div class="abt_us_work_name"><?= $about->param2Title ?></div>

                                <div class="abt_us_work_txt"><?= $about->param2Content ?>
                                </div>
                            </div>

                            <div class="col-4 abt_us_work_it">
                                <div class="abt_us_work_img fx-c">
                                    <img src="/img/about_us/about_us_3.png" alt="">
                                </div>

                                <div class="abt_us_work_name"><?= $about->param3Title ?></div>

                                <div class="abt_us_work_txt"><?= $about->param3Content ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- |========== About Us ==========| -->
    </section>

</main>
<!-- |********** Main **********| -->

views/site/delivery.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Delivery';
?>
<!-- |************************************************** Main **************************************************| -->
<main class="main">

    <!-- |=================================== Inner Banner ===================================| -->
    <section class="inner_bnr_sec">
        <div class="inner_bnr_bg bg-cover" style="background-image:url('/uploads/<?= $about->path ?>');     height: 400px;"></div>
        <!-- |========== Inner Banner ==========| -->
    </section>



    <!-- |=================================== About Us ===================================| -->
    <section class="abt_us_sec">
        <div class="product_bg bg-cover" style="background-image:url('/img/about_us/section_bg.png');"></div>

        <div class="container">
            <div class="abt_us">

                <div class="abt_us_desc">
                    <h3 class="inr_title abt_us_desc_ttl"><?= $about->title ?></h3>

                    <div class="abt_us_desc_cnt">
                        <?= $about->content ?>
                    </div>
                </div>


                <div class="abt_us_work">
                    <h2 class="base_title abt_us_work_ttl"><?= Yii::t('app','Для кого мы работаем?') ?></h2>

                    <div class="abt_us_work_cnt">
                        <div class="row">
                            <div class="col-4 abt_us_work_it">
                                <div class="abt_us_work_img fx-c">
                                    <img src="/img/about_us/about_us_1.png" alt="">
                                </div>

                                <div class="abt_us_work_name"><?= $about->param1Title ?></div>

                                <div class="abt_us_work_txt"><?= $about->param1Content ?>
                                </div>
                            </div>

                            <div class="col-4 abt_us_work_it">
                                <div class="abt_us_work_img fx-c">
                                    <img src="/img/about_us/about_us_2.png" alt="">
                                </div>

                                <div class="abt_us_work_name"><?= $about->param2Title ?></div>

                                <div class="abt_us_work_txt"><?= $about->param2Content ?>
                                </div>
                            </div>

                            <div class="col-4 abt_us_work_it">
                                <div class="abt_us_work_img fx-c">
                                    <img src="/img/about_us/about_us_3.png" alt="">
                                </div>

                                <div class="abt_us_work_name"><?= $about->param3Title ?></div>

                                <div class="abt_us_work_txt"><?= $about->param3Content ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- |========== About Us ==========| -->
    </section>

</main>
<!-- |********** Main **********| -->

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'DY Florist';
?>

<main class="main">

    <!-- |=================================== Banner ===================================| -->
    <section class="banner_sec">
        <div class="banner_bg_bx">
        <?php if(!empty($carousel)): ?>
        <?php foreach ($carousel as $k => $item): ?>
                <div class="banner_bg bg-cover <?= $k == 0 ? 'active' : '' ?>" style="background-image:url('/uploads/<?= $item->path ?>');"></div>
        <?php endforeach; ?>
        <?php endif; ?>
        </div>

        <div class="container">
            <div class="banner_bx us-n">
                <div class="banner">
                    <?php if(!empty($carousel)): ?>
                        <?php foreach ($carousel as $k => $item): ?>
                            <div class="banner_it">
                                <div class="banner_txt">
                                    <h2 class="banner_name"><?= $item->title ?></h2>
                                    <p class="banner_capt"><?= $item->content ?></p>
                                </div>

                                <div class="banner_more">
                                    <a href="<?= $item->url ?>" class="base_btn solid_pink"><?= Yii::t('app','подробнее') ?></a>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </div>


                <div class="banner_nav">
                    <div class="banner_btn fx-c prev">
                        <svg x="0px" y="0px" width="200px" height="200px" viewBox="0 0 477.175 477.175"
                             style="enable-background:new 0 0 477.175 477.175;" xml:space="preserve">
							<g>
                                <path d="M145.188,238.575l215.5-215.5c5.3-5.3,5.3-13.8,0-19.1s-13.8-5.3-19.1,0l-225.1,225.1c-5.3,5.3-5.3,13.8,0,19.1l225.1,225 c2.6,2.6,6.1,4,9.5,4s6.9-1.3,9.5-4c5.3-5.3,5.3-13.8,0-19.1L145.188,238.575z"/>
                            </g>
						</svg>
                    </div>
                    <div class="banner_btn fx-c next">
                        <svg x="0px" y="0px" width="200px" height="200px" viewBox="0 0 477.175 477.175"
                             style="enable-background:new 0 0 477.175 477.175;" xml:space="preserve">
							<g>
                                <path d="M360.731,229.075l-225.1-225.1c-5.3-5.3-13.8-5.3-19.1,0s-5.3,13.8,0,19.1l215.5,215.5l-215.5,215.5 c-5.3,5.3-5.3,13.8,0,19.1c2.6,2.6,6.1,4,9.5,4c3.4,0,6.9-1.3,9.5-4l225.1-225.1C365.931,242.875,365.931,234.275,360.731,229.075z"/>
                            </g>
						</svg>
                    </div>
                </div>
            </div>
        </div>
        <!-- |========== Banner ==========| -->
    </section>



    <!-- |=================================== Service ===================================| -->
    <section class="service_sec">
        <div class="container">

            <div class="service">
                <h2 class="base_title"><?= Yii::t('app','Наши услуги') ?></h2>


                <div class="service_cnt">
                    <div class="row_home">

                        <?php if(!empty($services)): ?>
                            <?php foreach ($services as $k => $item): ?>
                                <div class="col_home <?= (($k == 1) || ($k == 2)) ? 'sm' : 'lg' ?>">
                                    <div class="service_it bg-cover" style="background-image:url('/uploads/<?= $item->path ?>');">
                                        <div class="service_capt">
                                            <div class="service_name"><?= $item->title ?></div>

                                            <div class="service_txt">
                                               <?= mb_substr(strip_tags($item->content), 0,160); ?>..
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>


                <div class="service_more">
                    <a href="<?= Url::to(['/site/our-services']) ?>" class="base_btn border_white"><?= Yii::t('app','подробнее') ?></a>
                </div>
            </div>

        </div>
        <!-- |========== Service ==========| -->
    </section>



    <!-- |=================================== Product ===================================| -->
    <section class="product_sec">
        <div class="product_bg bg-cover" style="background-image:url('/img/home/section_bg_2.png');"></div>

        <div class="container">

            <div class="product">
                <h2 class="base_title"><?= Yii::t('app','Наша продукция') ?></h2>


                <div class="product_cnt">
                    <div class="row_home">
                <?php if(!empty($categories)): ?>
                    <?php foreach ($categories as $k => $item): ?>
                        <div class="col_home <?= (($k == 1) || ($k == 2)) ? 'sm' : 'lg' ?>">
                            <a href="<?php
                            if($k == 0 || $k == 1){
                                echo Url::to(['/product/category','id' => $item->id]);
                            } else{
                                echo Url::to(['/product/sub-category','id' => $item->id]);
                            }
                            ?>" class="product_it bg-cover" style="background-image:url('/uploads/<?= $item->path ?>');">
                                <div class="product_capt">
                                    <div class="product_name"><?= $item->title ?></div>
                                </div>
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>

                    </div>
                </div>
            </div>

        </div>
        <!-- |========== Product ==========| -->
    </section>



    <!-- |=================================== Advantage ===================================| -->
    <section class="advg_sec">
        <div class="container">

            <div class="advg">
                <h2 class="base_title"><?= Yii::t('app','Преимущества работы с нами') ?></h2>


                <div class="advg_cnt">

                    <?php if($advantages): ?>
                        <?php foreach ($advantages as $item): ?>
                         <div class="advg_it">
                        <div class="advg_img">
                            <img src="/uploads/<?= $item->path ?>" alt="">
                        </div>

                        <div class="advg_txt"><?= $item->title ?></div>
                    </div>
                        <?php endforeach; ?>
                    <?php endif;?>



                </div>
            </div>

        </div>
        <!-- |========== Advantage ==========| -->
    </section>

</main>

views/site/our-services.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 19.06.2018
 * Time: 13:41
 */

$this->title = 'Our Services';
?>

<main class="main">

    <!-- |=================================== Inner Banner ===================================| -->
    <section class="inner_bnr_sec">
        <div class="inner_bnr_bg bg-cover" style="background-image:url('/uploads/<?= $our_service->path ?>'); height: 400px"></div>
        <!-- |========== Inner Banner ==========| -->
    </section>



    <!-- |=================================== Service ===================================| -->
    <section class="svc_sec">
        <div class="container">

            <div class="svc">
                <div class="svc_ttl">

                    <h3 class="inr_title svc_ttl_name"><?= $our_service->title ?></h3>

                    <div class="svc_ttl_capt"><?= Yii::t('app','Главная / Наши услуги') ?></div>

                    <div class="svc_ttl_txt">
                        <?= $our_service->content ?>
                    </div>
                </div>


                <div class="svc_cnt">
                    <?php if($our_services): ?>
                    <?php foreach($our_services as $k => $item): ?>
                    <div class="svc_it <?= $k%2 == 0 ? ' ' : 'reverse' ?> ">
                        <div class="row">

                            <div class="svc_it_col col-lg-6">
                                <div class="svc_info" style="background: <?= $item->color ?>; border-color: <?= $item->color ?>;">
                                    <div class="svc_name"><?= $item->title ?></div>

                                    <div class="svc_txt">
                                        <?= strip_tags($item->content) ?>
                                    </div>
                                </div>
                            </div>


                            <div class="svc_it_col col-lg-6">
                                <div class="svc_img bg-cover" style="background-image:url('/uploads/<?= $item->path ?>');"></div>
                            </div>

                        </div>
                    </div>
                    <?php endforeach; ?>
                    <?php endif; ?>


                </div>
            </div>

        </div>
        <!-- |========== Service ==========| -->
    </section>

</main>